import {useEffect,useRef,useState} from 'react';
import type {Telemetry} from '../types';
/** RTSP and WebRTC must be integrated through an explicit browser-compatible gateway. */
export interface CameraAdapter {kind:'simulated'|'webcam'|'file'|'webrtc';stop:()=>void}
export function Camera({t,recording,replay}:{t:Telemetry|null;recording:boolean;replay:boolean}){
 const[source,setSource]=useState('simulated');const[camera,setCamera]=useState(1);const[detect,setDetect]=useState(true);const[tracking,setTracking]=useState(true);const[labels,setLabels]=useState(true);const[trails,setTrails]=useState(false);const[threshold,setThreshold]=useState(.5);const[error,setError]=useState('');const[file,setFile]=useState('');const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream>();const canvas=useRef<HTMLCanvasElement>(null);const value=useRef(t);value.current=t;
 useEffect(()=>{if(source!=='webcam')return;let gone=false;navigator.mediaDevices?.getUserMedia({video:true,audio:false}).then(s=>{if(gone){s.getTracks().forEach(t=>t.stop());return}stream.current=s;if(video.current)video.current.srcObject=s}).catch(e=>setError('Webcam unavailable: '+e.message));if(!navigator.mediaDevices)setError('Webcam requires localhost or HTTPS');return()=>{gone=true;stream.current?.getTracks().forEach(t=>t.stop())}},[source]);
 useEffect(()=>()=>{if(file)URL.revokeObjectURL(file)},[file]);
 useEffect(()=>{if(source!=='simulated')return;const el=canvas.current!;const ctx=el.getContext('2d')!;let id=0;
 const render=()=>{const w=el.width=el.clientWidth*devicePixelRatio,h=el.height=el.clientHeight*devicePixelRatio;const v=value.current;const time=v?.sim_time||0;const horizon=h*.43;ctx.fillStyle='#34556a';ctx.fillRect(0,0,w,horizon);const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#193848');sky.addColorStop(1,'#719197');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);ctx.fillStyle='#25382d';ctx.fillRect(0,horizon,w,h-horizon);
 ctx.strokeStyle='#405c47';ctx.lineWidth=1*devicePixelRatio;for(let i=-12;i<13;i++){ctx.beginPath();ctx.moveTo(w*.5+i*14,horizon);ctx.lineTo(w*.5+i*w*.22+(v?.position.x||0)%20,h);ctx.stroke()}for(let i=0;i<12;i++){const y=horizon+((i/12+time*.018)%1)**2*(h-horizon);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
 const offset=camera===2?.16:camera===3?-.13:0;for(let i=0;i<8;i++){const x=((i*.153+offset-(v?.position.x||0)*.0005+10)%1)*w;const bh=(.1+(i%3)*.04)*h;ctx.fillStyle=i%2?'#45505a':'#525d5f';ctx.fillRect(x,horizon-bh,w*.095,bh);ctx.fillStyle='#253641';for(let r=0;r<3;r++)for(let c=0;c<3;c++)ctx.fillRect(x+w*.012+c*w*.025,horizon-bh+h*.017+r*h*.025,w*.014,h*.013)}
 const dx=(.43+.12*Math.sin(time*.3))*w,dy=.4*h;ctx.strokeStyle='#0d1d24';ctx.lineWidth=5*devicePixelRatio;ctx.beginPath();ctx.moveTo(dx-w*.035,dy-h*.022);ctx.lineTo(dx+w*.035,dy+h*.022);ctx.moveTo(dx-w*.035,dy+h*.022);ctx.lineTo(dx+w*.035,dy-h*.022);ctx.stroke();ctx.fillStyle='#1b303b';ctx.fillRect(dx-w*.014,dy-h*.018,w*.028,h*.036);for(const x of [-1,1])for(const y of [-1,1]){ctx.beginPath();ctx.ellipse(dx+x*w*.035,dy+y*h*.022,w*.027,h*.008,0,0,Math.PI*2);ctx.strokeStyle='#83aeb7';ctx.lineWidth=1.5*devicePixelRatio;ctx.stroke()}
 ctx.fillStyle='#61788a';ctx.fillRect(.73*w,.67*h,.11*w,.06*h);ctx.fillStyle='#0f1e27';ctx.fillRect(.755*w,.645*h,.06*w,.025*h);ctx.fillStyle='#10191d';ctx.beginPath();ctx.arc(.75*w,.735*h,.014*w,0,7);ctx.arc(.82*w,.735*h,.014*w,0,7);ctx.fill();id=requestAnimationFrame(render)};render();return()=>cancelAnimationFrame(id)},[source,camera]);
 const paths=useRef<Record<number,number[][]>>({});const lastTime=useRef(-1);
 useEffect(()=>{if(!t)return;if(t.sim_time<lastTime.current)paths.current={};if(t.sim_time!==lastTime.current){for(const d of t.detections)paths.current[d.track_id]=[...(paths.current[d.track_id]||[]),[d.bbox[0]+d.bbox[2]/2,d.bbox[1]+d.bbox[3]/2]].slice(-70)}lastTime.current=t.sim_time},[t]);
 const v=t;return <><div className="camera-viewport">{source==='simulated'?<canvas ref={canvas}/>:<video ref={video} src={source==='file'?file:undefined} autoPlay muted loop playsInline controls={source==='file'}/>}<div className="camera-shade"/><div className="hud-left">ALT <b>{v?.position.alt.toFixed(1)||'—'} m</b><br/>SPD <b>{v?Math.hypot(v.velocity.x,v.velocity.y,v.velocity.z).toFixed(1):'—'} m/s</b><br/>HDG <b>{v?.orientation.yaw.toFixed(1)||'—'}°</b></div><div className="hud-heading">240 ┊ 270 ┊ <b>{v?.orientation.yaw.toFixed(0).padStart(3,'0')}°</b> ┊ 330 ┊ 360</div><div className="crosshair">┼</div><span className="source-label">{source==='simulated'?`SYNTHETIC CAMERA ${camera}`:source.toUpperCase()} · {replay?'TELEMETRY REPLAY':'SIMULATION'}</span>
 {detect&&source==='simulated'&&v?.detections.filter(d=>d.confidence>=threshold).map(d=><div key={d.track_id} className="detection" style={{left:d.bbox[0]*100+'%',top:d.bbox[1]*100+'%',width:d.bbox[2]*100+'%',height:d.bbox[3]*100+'%',borderColor:d.class==='Drone'?'#00ee99':'#37aeff'}}>{labels&&<span>{d.class} {d.confidence.toFixed(2)} {tracking?`#${d.track_id}`:''}</span>}</div>)}{source==='simulated'&&detect&&tracking&&trails&&<svg className="track-overlay" viewBox="0 0 100 100" preserveAspectRatio="none">{v?.detections.filter(d=>d.confidence>=threshold).map(d=><polyline key={d.track_id} points={(paths.current[d.track_id]||[]).map(p=>`${p[0]*100},${p[1]*100}`).join(' ')} fill="none" stroke="#70fbbb" strokeWidth=".2"/>)}</svg>}<div className="hud-bottom"><span className={recording?'red':'green'}>● {recording?'TELEMETRY REC':'LIVE VIEW'}</span><span>T+ {v?.sim_time.toFixed(1)||'0.0'} s</span><span>CAM {camera} ▣</span></div>{error&&<div className="camera-error">{error}</div>}</div>
 <div className="camera-tools"><select aria-label="Camera view" value={camera} onChange={e=>setCamera(+e.target.value)}>{[1,2,3].map(i=><option key={i} value={i}>Camera {i}</option>)}</select><select aria-label="Camera source" value={source} onChange={e=>{setError('');setSource(e.target.value)}}><option value="simulated">Synthetic scene</option><option value="webcam">Local webcam</option><option value="file">Video file</option></select>{source==='file'&&<input aria-label="Video file" type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&setFile(URL.createObjectURL(e.target.files[0]))}/>}
 <label><input type="checkbox" checked={detect} onChange={e=>setDetect(e.target.checked)}/>Detection</label><label><input type="checkbox" checked={tracking} onChange={e=>setTracking(e.target.checked)}/>Track</label><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/>Labels</label><label><input type="checkbox" checked={trails} onChange={e=>setTrails(e.target.checked)}/>Trails</label><label>Confidence <input aria-label="Confidence threshold" type="range" min="0" max="1" step=".01" value={threshold} onChange={e=>setThreshold(+e.target.value)}/>{threshold.toFixed(2)}</label></div></>
}
