import {useEffect,useRef,useState} from 'react';
import {api,exportSession} from '../services';
import {useTelemetry} from '../store';
import type {Session,Telemetry} from '../types';
export function Replay({notify}:{notify:(s:string)=>void}){const[sessions,setSessions]=useState<Session[]>([]);const[chosen,setChosen]=useState('');const[points,setPoints]=useState<Telemetry[]>([]);const[index,setIndex]=useState(0);const[playing,setPlaying]=useState(false);const[speed,setSpeed]=useState(1);const[loading,setLoading]=useState(false);const timing=useRef<number[]>([]);const cursor=useRef(0);const replay=useTelemetry(s=>s.replay);
 const refresh=()=>api<Session[]>('/sessions').then(setSessions).catch(e=>notify(e.message));useEffect(()=>{refresh()},[]);
 const load=async()=>{if(!chosen)return;setLoading(true);setPlaying(false);try{const all:Telemetry[]=[];let offset=0;while(true){const part=await api<Telemetry[]>(`/sessions/${chosen}/points?offset=${offset}&limit=10000`);all.push(...part);if(part.length<10000)break;offset+=part.length}if(!all.length)throw new Error('This session contains no telemetry samples');timing.current=[0];for(let i=1;i<all.length;i++)timing.current.push(timing.current[i-1]+Math.max(1/all[i].rate,all[i].sim_time-all[i-1].sim_time));setPoints(all);cursor.current=0;setIndex(0);useTelemetry.getState().setReplay(true);useTelemetry.getState().display(all[0]);notify(`Loaded ${all.length.toLocaleString()} recorded samples`)}catch(e){notify((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{if(!playing||!points.length||!replay)return;let id=0,last=performance.now(),elapsed=timing.current[cursor.current];const tick=(now:number)=>{elapsed+=(now-last)*speed/1000;last=now;let i=cursor.current;while(i<points.length-1&&timing.current[i+1]<=elapsed)i++;if(i!==cursor.current){cursor.current=i;setIndex(i);useTelemetry.getState().display(points[i])}if(i===points.length-1){setPlaying(false);return}id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[playing,speed,points,replay]);
 const seek=(i:number)=>{setPlaying(false);cursor.current=i;setIndex(i);useTelemetry.getState().clear();useTelemetry.getState().display(points[i])};
 return <div className="replay"><div className="button-row"><select aria-label="Recorded session" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Select a recorded session</option>{sessions.map(s=><option key={s.id} value={s.id}>{new Date(s.start_time).toLocaleString()} · {s.samples} samples · {s.status}</option>)}</select><button onClick={refresh}>Refresh</button><button disabled={!chosen||loading} onClick={load}>{loading?'Loading…':'Load replay'}</button>{['json','csv'].map(f=><button key={f} disabled={!chosen} onClick={()=>exportSession(chosen,f).catch(e=>notify(e.message))}>{f.toUpperCase()} ↓</button>)}</div>
 {replay&&<><div className="button-row"><strong className="amber">REPLAY · commands disabled</strong><button onClick={()=>{if(index===points.length-1)seek(0);setPlaying(!playing)}}>{playing?'Pause replay':'Play replay'}</button><button onClick={()=>seek(0)}>Stop</button><select aria-label="Replay speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.25,.5,1,2,5,10].map(s=><option key={s}>{s}</option>)}</select><span>× speed · sample {index+1}/{points.length}</span><button onClick={()=>{setPlaying(false);useTelemetry.getState().setReplay(false)}}>Return to live</button></div><input className="timeline" aria-label="Replay timeline" type="range" min="0" max={Math.max(0,points.length-1)} value={index} onChange={e=>seek(+e.target.value)}/></>}
 {!replay&&<p className="muted">Record a flight, then replay the captured telemetry through the graphs, map, HUD and attitude view.</p>}</div>
}
