import {useEffect,useMemo,useRef,useState, type ReactNode} from 'react';
import {useTelemetry,connectTelemetry} from './store';
import {api,flatten,saveFile} from './services';
import type {Telemetry,Alert,Mission,Settings,Waypoint} from './types';
import {Chart} from './components/Chart';
import {Camera} from './components/Camera';
import {FlightMap} from './components/Map';
import {Attitude} from './components/Attitude';
import {Replay} from './components/Replay';
function Panel({title,extra,children,className=''}:{title:string;extra?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-title"><h2>{title}</h2>{extra}</div>{children}</section>}
const scenarios=['HOVER','TAKEOFF','CLIMB','CRUISE','ORBIT','TURN','DESCENT','LANDING','GPS FAILURE','LOW BATTERY','COMMUNICATION FAILURE','SENSOR ANOMALY'];
const modes=['MANUAL','STABILIZE','ALTITUDE HOLD','POSITION HOLD','AUTO'];
const f=(v:number|undefined,n=1)=>v===undefined?'—':v.toFixed(n);
function Stat({label,value,unit=''}:{label:string;value:ReactNode;unit?:string}){return <div className="stat"><span>{label}</span><b>{value} <small>{unit}</small></b></div>}
function Raw({t,notify}:{t:Telemetry|null;notify:(s:string)=>void}){const[q,setQ]=useState('');const[paused,setPaused]=useState(false);const freeze=useRef(t);if(!paused)freeze.current=t;const flat=flatten(freeze.current||{});const rows=Object.entries(flat).filter(([k])=>!k.includes('detections')&&k.toLowerCase().includes(q.toLowerCase()));return <><div className="raw-toolbar"><input aria-label="Search telemetry" placeholder="Filter fields…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(flat,null,2)).then(()=>notify('Telemetry copied')).catch(()=>notify('Clipboard unavailable'))}>Copy</button><button onClick={()=>saveFile('telemetry-snapshot.csv','field,value\n'+rows.map(([k,v])=>`${k},${JSON.stringify(String(v))}`).join('\n'),'text/csv')}>CSV</button></div><div className="raw-table">{rows.map(([key,value])=><div key={key}><span>{key}</span><b>{typeof value==='number'?value.toFixed(3):String(value)}</b></div>)}</div></>}
export default function App(){const state=useTelemetry();const t=state.current;const[toast,setToast]=useState('');const[tab,setTab]=useState('alerts');const[alerts,setAlerts]=useState<Alert[]>([]);const[events,setEvents]=useState<any[]>([]);const[missions,setMissions]=useState<Mission[]>([]);const[mission,setMission]=useState('');const[waypoints,setWaypoints]=useState<Waypoint[]>([]);const[addWaypoint,setAddWaypoint]=useState(false);const[missionName,setMissionName]=useState('Survey flight');const[description,setDescription]=useState('');const[targetAlt,setTargetAlt]=useState(150);const[maxSpeed,setMaxSpeed]=useState(20);const[settingsOpen,setSettingsOpen]=useState(false);const[settings,setSettings]=useState<Settings>({rate:50,speed:1,seed:42,battery_warning:30,rssi_warning:-85,gps_warning:6});const[theme,setTheme]=useState(localStorage.getItem('theme')||'dark');const[windowSeconds,setWindowSeconds]=useState(60);const[chartPaused,setChartPaused]=useState(false);const[autoscale,setAutoscale]=useState(true);const frozen=useRef<Telemetry[]>([]);const[controls,setControls]=useState({throttle:50,yaw:0,pitch:0,roll:0});const[commandStatus,setCommandStatus]=useState('Awaiting command');const[busy,setBusy]=useState(false);const[apiKey,setApiKey]=useState(sessionStorage.getItem('api_key')||'');const[clock,setClock]=useState(new Date());const[recordStart,setRecordStart]=useState(Date.now());const[lastAlert,setLastAlert]=useState('');
 const notify=(message:string)=>setToast(message);
 useEffect(()=>connectTelemetry(),[]);
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer)}},[toast]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
 const refresh=()=>Promise.all([api<Alert[]>('/alerts'),api<Mission[]>('/missions'),api<any[]>('/events')]).then(([a,m,e])=>{setAlerts(a);setMissions(m);setEvents(e)}).catch(()=>{});
 useEffect(()=>{refresh();api<Settings>('/settings').then(setSettings).catch(()=>{});const timer=setInterval(refresh,2000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const active=alerts.find(a=>a.active&&!a.acknowledged);if(active&&active.id!==lastAlert){notify(active.message);setLastAlert(active.id)}},[alerts]);
 useEffect(()=>{if(!mission){setWaypoints([]);return}api<Waypoint[]>(`/missions/${mission}/waypoints`).then(setWaypoints).catch(e=>notify(e.message))},[mission]);
 useEffect(()=>{if(state.recording)setRecordStart(Date.now())},[state.recording]);
 const selectedMission=missions.find(m=>m.id===mission);
 if(!chartPaused)frozen.current=state.history;
 const chartData=useMemo(()=>{const history=chartPaused?frozen.current:state.history;const end=history.at(-1)?.sim_time||0;return history.filter(p=>p.sim_time>=end-windowSeconds)},[state.history,chartPaused,windowSeconds]);
 const active=alerts.filter(a=>a.active);const critical=active.some(a=>a.severity==='CRITICAL');
 const command=async(type:string,value?:unknown)=>{if(state.replay)return;setBusy(true);try{const r=await api('/commands','POST',{type,value});setCommandStatus(`${r.type} · ${r.status} · ${r.id.slice(0,8)}`);notify(r.error||`${r.type} accepted`);if(type==='RESET'&&r.status==='ACCEPTED'){setControls({throttle:50,yaw:0,pitch:0,roll:0});useTelemetry.getState().clear()}refresh()}catch(e){notify((e as Error).message)}finally{setBusy(false)}};
 const disabled=state.replay||state.connection!=='CONNECTED'||busy;
 const record=async(action:string)=>{try{await api('/sessions/'+action+(action==='start'&&mission?'?mission_id='+mission:''),'POST');notify('Recording '+action);refresh()}catch(e){notify((e as Error).message)}};
 const createMission=async()=>{try{const m=await api<Mission>('/missions','POST',{name:missionName,description,target_altitude:targetAlt,max_speed:maxSpeed});setMission(m.id);await refresh();notify('Mission created')}catch(e){notify((e as Error).message)}};
 const waypoint=async(lat:number,lon:number)=>{if(!addWaypoint)return;if(!mission){notify('Select a mission before adding waypoints');return}try{const w=await api<Waypoint>(`/missions/${mission}/waypoints`,'POST',{lat,lon,altitude:selectedMission?.target_altitude||150});setWaypoints(wp=>[...wp,w])}catch(e){notify((e as Error).message)}};
 return <div className="app-shell"><header><div className="brand"><svg viewBox="0 0 50 45" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 13L36 33M14 33L36 13"/><rect x="19" y="17" width="12" height="12" rx="3"/>{[[11,10],[39,10],[11,35],[39,35]].map(([x,y])=><ellipse key={x+','+y} cx={x} cy={y} rx="9" ry="4"/>)}</g></svg><div><h1>AERIAL ROBOTICS PLATFORM</h1><p>UAV Flight Test & Telemetry Control</p></div></div><div className="header-state"><b className={state.connection==='CONNECTED'?'green':'red'} data-testid="connection">● {state.connection}</b><span>Vehicle ID: <b>DR-001</b></span><span>Mode: <b className="mode-tag">{t?.mode||'—'}</b></span></div><div className="header-stats"><Stat label="RSSI" value={f(t?.rssi,0)} unit="dBm"/><Stat label="Battery" value={f(t?.battery.percentage,0)+'%'}/><Stat label="TX Rate" value={t?.rate||'—'} unit="Hz"/><div className="clock">{clock.toLocaleDateString('en-CA')}　{clock.toLocaleTimeString('en-GB')}<small>{Intl.DateTimeFormat().resolvedOptions().timeZone}</small></div></div></header>
 <div className="instrument-bar"><span className="simulation-tag">◇ SIMULATION MODE</span><span className={state.replay?'amber':'green'}>{state.replay?'RECORDED TELEMETRY':'LIVE TELEMETRY'}</span>{t?.paused&&<span className="amber">SIMULATOR PAUSED</span>}{!state.simConnected&&<span className="red">SIMULATOR DISCONNECTED</span>}<div className="spacer"/><label>Graph window <select aria-label="Graph window" value={windowSeconds} onChange={e=>setWindowSeconds(+e.target.value)}>{[10,30,60,300,600].map(s=><option key={s} value={s}>{s<60?s+' sec':s/60+' min'}</option>)}</select></label><button onClick={()=>setChartPaused(!chartPaused)}>{chartPaused?'Resume graphs':'Pause graphs'}</button><button onClick={()=>{useTelemetry.getState().clear();frozen.current=[]}}>Clear</button><label><input type="checkbox" checked={autoscale} onChange={e=>setAutoscale(e.target.checked)}/>Autoscale</label></div>
 <div className="top-charts">{[{title:'IMU – Gyroscope (°/s)',fields:['gyro.x','gyro.y','gyro.z']},{title:'IMU – Accelerometer (m/s²)',fields:['acceleration.x','acceleration.y','acceleration.z']},{title:'Body Orientation – X (°)',fields:['orientation.roll']},{title:'Body Orientation – Y (°)',fields:['orientation.pitch'],colors:['#ffad39']},{title:'Body Orientation – Z (°)',fields:['orientation.yaw'],colors:['#00adff']}].map(c=><Panel key={c.title} title={c.title} extra={<span className="chart-current">{c.fields.map(field=>f(field.split('.').reduce((v:any,k)=>v?.[k],t))).join(' / ')}</span>}><Chart data={chartData} fields={c.fields} colors={c.colors} autoscale={autoscale}/></Panel>)}</div>
 <main className="dashboard"><aside className="left-column"><Panel title="VEHICLE STATE"><div className={'armed '+(t?.armed?'green':'amber')}>◉ {t?.state||'CONNECTING'}</div><div className="state-grid"><Stat label="Mode" value={t?.mode||'—'}/><Stat label="Health" value={t?.health||'—'}/><Stat label="GPS Fix" value={t?.gps.fix||'—'}/></div></Panel>
 <Panel title="ALTITUDE" extra={<span className="green">↑ {f(t?.velocity.z)} m/s</span>}><div className="altitude" data-testid="altitude">{f(t?.position.alt)}<small> m AGL</small></div><Chart data={chartData} fields={['position.alt']} height={91}/><div className="summary-row"><span>MIN {chartData.length?f(Math.min(...chartData.map(p=>p.position.alt))):'—'}</span><span>MAX {chartData.length?f(Math.max(...chartData.map(p=>p.position.alt))):'—'}</span><span>AVG {chartData.length?f(chartData.reduce((s,p)=>s+p.position.alt,0)/chartData.length):'—'}</span></div></Panel>
 <Panel title="XY POSITION & VELOCITY"><div className="state-grid two"><Stat label="X east" value={f(t?.position.x)} unit="m"/><Stat label="Y north" value={f(t?.position.y)} unit="m"/><Stat label="Velocity X" value={f(t?.velocity.x)} unit="m/s"/><Stat label="Velocity Y" value={f(t?.velocity.y)} unit="m/s"/></div><svg viewBox="0 0 250 88" className="trajectory" aria-label="Local XY trajectory"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="#15384b" strokeWidth=".6"/></pattern></defs><rect width="250" height="88" fill="url(#grid)"/>{(()=>{if(!chartData.length)return null;const xs=chartData.map(p=>p.position.x),ys=chartData.map(p=>p.position.y);const minX=Math.min(...xs)-5,maxX=Math.max(...xs)+5,minY=Math.min(...ys)-5,maxY=Math.max(...ys)+5;return <polyline points={chartData.map(p=>`${10+(p.position.x-minX)/(maxX-minX)*230},${78-(p.position.y-minY)/(maxY-minY)*68}`).join(' ')} fill="none" stroke="#00e69a" strokeWidth="1.5"/>})()}<text x="5" y="12" fill="#91b6cc" fontSize="8">N ↑ / E →</text></svg></Panel>
 <Panel title="BATTERY / SIGNAL / TELEMETRY"><div className="power-row"><div className="battery-ring" style={{background:`conic-gradient(#00e69a ${(t?.battery.percentage||0)*3.6}deg,#153041 0)`}}><b>{f(t?.battery.percentage,0)}%</b></div><Stat label="RSSI" value={f(t?.rssi,0)} unit="dBm"/><Stat label="Telemetry" value={t?.rate||'—'} unit="Hz"/></div><div className="state-grid two"><Stat label="Voltage / current" value={`${f(t?.battery.voltage)} V / ${f(t?.battery.current)} A`}/><Stat label="Latency (sim)" value={f(t?.latency,0)} unit="ms"/><Stat label="Generated / lost (sim)" value={`${t?.sequence||0} / ${t?.packets_lost||0}`}/><Stat label="Packet loss" value={f(t?.packet_loss)} unit="%"/></div></Panel></aside>
 <div className="center-column"><Panel title="● LIVE CAMERA FEED" className="camera-panel" extra={<span className="cyan">GENERATED SCENE · LOCAL VIDEO READY</span>}><Camera t={t} recording={!!state.recording} replay={state.replay}/></Panel><div className="bottom-panels"><Panel title="MAP & LOCALIZATION" extra={<span className="green">◉ {t?.gps.fix||'—'}</span>}><FlightMap t={t} history={state.history} waypoints={waypoints} onWaypoint={waypoint}/><div className="summary-row"><span>{f(t?.position.lat,6)}° N</span><span>{f(t?.position.lon,6)}° E</span></div></Panel><Panel title="ATTITUDE / ORIENTATION" extra={<span className="cyan">3D</span>}><Attitude t={t}/></Panel></div></div>
 <aside className="right-column"><Panel title="CONTROL & COMMAND" extra={<span className="green">● Simulator</span>}><fieldset disabled={disabled}><div className="command-buttons"><button className="primary" onClick={()=>command('ARM')}>⌘ ARM</button><button onClick={()=>command('DISARM')}>DISARM</button><button className="danger" onClick={()=>command('EMERGENCY_STOP')}>⚠ EMERGENCY STOP</button></div><label className="control-label">FLIGHT MODE<select aria-label="Flight mode" value={t?.mode||'MANUAL'} onChange={e=>command('SET_MODE',e.target.value)}>{modes.map(m=><option key={m}>{m}</option>)}</select></label><div className="slider throttle"><label>THROTTLE <b>{controls.throttle}%</b></label><input aria-label="Throttle" type="range" min="0" max="100" value={controls.throttle} onChange={e=>setControls({...controls,throttle:+e.target.value})}/><div className="range-label"><span>0%</span><span>100%</span></div></div><div className="axes-controls">{(['yaw','pitch','roll'] as const).map(k=><div className="slider" key={k}><label>{k.toUpperCase()} <b>{controls[k]}%</b></label><input aria-label={k} type="range" min="-100" max="100" value={controls[k]} onChange={e=>setControls({...controls,[k]:+e.target.value})}/><div className="range-label"><span>−100</span><span>100</span></div></div>)}</div><div className="button-row"><button onClick={()=>command('SET_CONTROL',controls)}>Apply controls</button><button onClick={()=>command('RTH')}>⌂ Return home</button><button onClick={()=>command('LAND')}>Land</button></div><label className="control-label">SCENARIO<select aria-label="Simulation scenario" value={t?.scenario||'CRUISE'} onChange={e=>command('SET_SCENARIO',e.target.value)}>{scenarios.map(s=><option key={s}>{s}</option>)}</select></label><div className="button-row"><button onClick={()=>command(t?.paused?'RESUME':'PAUSE')}>{t?.paused?'Resume simulation':'Pause simulation'}</button><button onClick={()=>command('RESET')}>Reset vehicle</button><button onClick={()=>setSettingsOpen(true)}>⚙ Settings</button></div></fieldset><div className="command-status" role="status">{commandStatus}</div></Panel>
 <Panel title="RAW TELEMETRY" extra={<span className="green">● {state.replay?'Replay':'Live'}</span>}><Raw t={t} notify={notify}/></Panel></aside></main>
 <div className="session-bar"><span className={state.recording?'red':'muted'}>● {state.recording?`TELEMETRY REC ${state.recordPaused?'PAUSED':Math.floor((clock.getTime()-recordStart)/1000)+'s'}`:'RECORDER READY'}</span><button disabled={state.replay||!!state.recording} onClick={()=>record('start')}>Start recording</button><button disabled={!state.recording} onClick={()=>record(state.recordPaused?'resume':'pause')}>{state.recordPaused?'Resume recording':'Pause recording'}</button><button disabled={!state.recording} onClick={()=>record('stop')}>Stop recording</button><div className="spacer"/><button onClick={()=>setTab('replay')}>▷ Mission replay</button><button onClick={()=>setTab('missions')}>Missions</button><button onClick={()=>setTab('alerts')}>Alerts ({active.length})</button><button onClick={()=>setTab('gps')}>GPS / satellites</button></div>
 <section className="workspace-panel"><nav>{['alerts','replay','missions','gps','events'].map(s=><button className={tab===s?'active':''} key={s} onClick={()=>setTab(s)}>{s.toUpperCase()}</button>)}</nav><div style={{display:tab==='replay'?'block':'none'}}><Replay notify={notify}/></div>
 {tab==='alerts'&&<div className="alert-list">{!alerts.length?<div className="empty"><b className="green">✓ SYSTEM NOMINAL</b><span>Alert history appears here. Try a GPS, battery or communication failure scenario.</span></div>:alerts.map(a=><div className="alert-row" key={a.id}><span className={a.severity==='CRITICAL'?'red':'amber'}>● {a.severity}</span><span>{a.message}</span><small>{new Date(a.timestamp).toLocaleTimeString()} · {a.active?'ACTIVE':'RESOLVED'}</small><button disabled={a.acknowledged} onClick={()=>api(`/alerts/${a.id}/ack`,'POST').then(refresh).catch(e=>notify(e.message))}>{a.acknowledged?'Acknowledged':'Acknowledge'}</button></div>)}</div>}
 {tab==='missions'&&<div className="missions-workspace"><div><h3>New mission</h3><input aria-label="Mission name" placeholder="Mission name" value={missionName} onChange={e=>setMissionName(e.target.value)}/><input aria-label="Mission description" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><div className="button-row"><label>Target altitude (m)<input aria-label="Target altitude" type="number" min="0" max="500" value={targetAlt} onChange={e=>setTargetAlt(+e.target.value)}/></label><label>Max speed (m/s)<input aria-label="Maximum speed" type="number" min="1" max="50" value={maxSpeed} onChange={e=>setMaxSpeed(+e.target.value)}/></label></div><button onClick={createMission}>Create mission</button><small>Mission targets and waypoints are planning annotations; they do not fly the vehicle.</small></div><div><h3>Mission manager</h3><select aria-label="Selected mission" value={mission} onChange={e=>setMission(e.target.value)}><option value="">Select mission</option>{missions.map(m=><option key={m.id} value={m.id}>{m.name} · {m.status}</option>)}</select>{selectedMission&&<><p>{selectedMission.description}</p><div className="button-row">{({'PLANNED':['RUNNING','ABORTED'],'RUNNING':['PAUSED','COMPLETED','ABORTED'],'PAUSED':['RUNNING','COMPLETED','ABORTED']} as Record<string,string[]>)[selectedMission.status]?.map(s=><button key={s} onClick={()=>api(`/missions/${mission}`,'PATCH',{status:s}).then(refresh).catch(e=>notify(e.message))}>{s}</button>)}</div><label><input type="checkbox" checked={addWaypoint} onChange={e=>setAddWaypoint(e.target.checked)}/> Add waypoints by clicking the map</label>{waypoints.map((w,i)=><div className="waypoint-row" key={w.id}>{i+1}. {w.lat.toFixed(5)}, {w.lon.toFixed(5)} · {w.altitude} m <button onClick={()=>api('/waypoints/'+w.id,'DELETE').then(()=>setWaypoints(waypoints.filter(p=>p.id!==w.id))).catch(e=>notify(e.message))}>Remove</button></div>)}<h3>Timeline</h3>{events.filter(e=>e.mission_id===mission).map(e=><p key={e.id}>{new Date(e.timestamp).toLocaleTimeString()} · {e.message}</p>)}</>}</div></div>}
 {tab==='gps'&&<div className="gps-workspace"><svg viewBox="0 0 220 220" width="220" aria-label="Simulated satellite skyplot">{[35,65,95].map(r=><circle key={r} cx="110" cy="110" r={r} stroke="#205069" fill="none"/>)}<path d="M110 15V205M15 110H205" stroke="#205069"/><text x="106" y="12" fill="#b3d6e8">N</text>{Array.from({length:t?.gps.satellites||0},(_,i)=>{const a=i*2.4+(t?.sim_time||0)*.005,r=25+(i%4)*19;return <g key={i}><circle cx={110+Math.cos(a)*r} cy={110+Math.sin(a)*r} r="7" fill="#00b584"/><text x={107+Math.cos(a)*r} y={113+Math.sin(a)*r} fontSize="8" fill="white">{i+1}</text></g>})}</svg><div><h3>GPS / LOCALIZATION</h3><Stat label="Fix" value={t?.gps.fix||'—'}/><Stat label="Satellites" value={t?.gps.satellites||0}/><Stat label="HDOP" value={f(t?.gps.hdop)}/><Stat label="Coordinates" value={`${f(t?.position.lat,6)}, ${f(t?.position.lon,6)}`}/><p className="muted">Satellite positions are a synthetic skyplot; count and fix follow simulator state.</p></div></div>}
 {tab==='events'&&<div className="event-list">{events.map(e=><div key={e.id}><small>{new Date(e.timestamp).toLocaleTimeString()}</small><b>{e.kind}</b><span>{e.message}</span></div>)}</div>}</section>
 <footer><span>Flight Test</span><span>Mission: {selectedMission?.name||'Free flight'}</span><span>Target Altitude: {selectedMission?.target_altitude||150} m</span><span>Max Speed: {selectedMission?.max_speed||20} m/s</span><div className="spacer"/><b className={state.connection!=='CONNECTED'||critical?'red':active.length?'amber':'green'}>{state.connection!=='CONNECTED'?'● LINK OFFLINE':critical?'● SYSTEM CRITICAL':active.length?'● SYSTEM WARNING':'● SYSTEM NOMINAL'}</b></footer>
 {toast&&<div className="toast" role="alert">{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}>×</button></div>}
 {(settingsOpen||state.connection==='DISCONNECTED')&&<button className="settings-float" onClick={()=>setSettingsOpen(true)}>Connection / settings</button>}
 {settingsOpen&&<div className="modal-backdrop"><div className="settings-modal"><div className="panel-title"><h2>SYSTEM SETTINGS</h2><button onClick={()=>setSettingsOpen(false)}>Close</button></div><p className="simulation-tag">SIMULATOR ADAPTER ONLY · DR-001</p>{Object.entries(settings).map(([k,v])=><label className="settings-row" key={k}>{k.replaceAll('_',' ')}<input aria-label={k} type="number" step={k==='speed'?'.25':'1'} value={v} onChange={e=>setSettings({...settings,[k]:+e.target.value})}/></label>)}<label className="settings-row">Appearance<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="dark">Dark instrumentation</option><option value="light">Light</option></select></label><p className="muted">Metric units · graph history configured in toolbar · map provider and cameras configured in their panels. Seed applies after Reset.</p><button className="primary" onClick={()=>api('/settings','PUT',settings).then(()=>{notify('Settings saved');setSettingsOpen(false)}).catch(e=>notify(e.message))}>Save settings</button><hr/><label>API key (optional server authentication)<input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)}/></label><button onClick={()=>{sessionStorage.setItem('api_key',apiKey);location.reload()}}>Reconnect with key</button><p className="muted">If the backend is unavailable, start it on port 8000. WebSocket retries automatically.</p></div></div>}
 </div>
}
