import {test,expect} from '@playwright/test';
test('live telemetry, controls, alerts, recording and replay',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');
 await expect(page.getByTestId('connection')).toHaveText('● CONNECTED');await expect(page.getByTestId('telemetry-chart')).toHaveCount(6);await expect(page.getByTestId('flight-map').locator('.vehicle-marker')).toBeVisible();await expect(page.getByTestId('attitude-view').locator('canvas')).toBeVisible();
 const before=await page.getByTestId('altitude').textContent();await expect.poll(()=>page.getByTestId('altitude').textContent()).not.toBe(before);
 await page.getByRole('button',{name:'Pause simulation',exact:true}).click();await expect(page.getByRole('button',{name:'Resume simulation',exact:true})).toBeVisible();await page.getByRole('button',{name:'Resume simulation',exact:true}).click();
 await page.getByRole('button',{name:'Start recording',exact:true}).click();await expect(page.getByRole('button',{name:'Stop recording',exact:true})).toBeEnabled();
 await page.getByLabel('Simulation scenario').selectOption('SENSOR ANOMALY');await expect(page.getByLabel('Simulation scenario')).toHaveValue('SENSOR ANOMALY');
 await page.getByRole('button',{name:'EMERGENCY STOP'}).click();await expect(page.locator('.armed')).toHaveText('◉ EMERGENCY');await expect(page.locator('.alert-row').filter({hasText:'Emergency stop latched'})).toBeVisible();
 await page.getByRole('button',{name:'Reset vehicle',exact:true}).click();await expect(page.locator('.armed')).toHaveText('◉ FLIGHT');
 await page.getByRole('button',{name:'Stop recording',exact:true}).click();await page.getByRole('button',{name:'▷ Mission replay',exact:true}).click();await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByLabel('Recorded session').locator('option')).not.toHaveCount(1);await page.getByLabel('Recorded session').selectOption({index:1});await page.getByRole('button',{name:'Load replay',exact:true}).click();await expect(page.getByText('REPLAY · commands disabled')).toBeVisible();await expect(page.getByRole('button',{name:'⌘ ARM',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Play replay',exact:true}).click();await expect.poll(()=>page.getByLabel('Replay timeline').inputValue()).not.toBe('0');await page.getByRole('button',{name:'Return to live',exact:true}).click();
 await page.screenshot({path:'../docs/dashboard.png',fullPage:true});expect(errors).toEqual([]);
});
test('mission creation and mobile layout',async({page})=>{await page.goto('/');await expect(page.getByTestId('connection')).toHaveText('● CONNECTED');await page.getByRole('button',{name:'MISSIONS',exact:true}).click();await page.getByLabel('Mission name',{exact:true}).fill('Browser integration mission');await page.getByRole('button',{name:'Create mission',exact:true}).click();await expect(page.getByLabel('Selected mission')).not.toHaveValue('');await page.getByRole('button',{name:'RUNNING',exact:true}).click();await expect(page.getByLabel('Selected mission').locator('option:checked')).toContainText('RUNNING');await page.setViewportSize({width:390,height:844});await expect(page.getByTestId('flight-map')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
